aug_mode: focusmix
aug_prob: 0.5
backbone: convnextv2
batch_size: 32
class_weights:
- 0.7807183265686035
- 1.3905723094940186
coatnet_model_name: coatnet_0_rw_224.sw_in1k
compactness: 10.0
cutmix_alpha: 1.0
data_dir: dataset
focal_gamma: 2.0
image_size: 224
label_smoothing: 0.0
llrd: 0.75
lr: 0.0001
max_epochs: 30
mha_stage: 2
mix_prob: 0.5
mixing: none
mixup_alpha: 0.2
n_segments: 50
num_classes: 2
num_heads: 8
num_workers: 2
paste_ratio: 0.25
pretrained: true
stain_aug_prob: 0.5
stain_sigma_mean: 0.15
stain_sigma_std: 0.1
use_focal_loss: true
use_mha: false
use_robust_aug: true
warmup_epochs: 3
weight_decay: 0.05
